os:
  - linux
  - osx

language: go
go:
- "1.10"

addons:
  apt:
    update: true
    packages:
      - trash-cli

before_install:
  - if [ $TRAVIS_OS_NAME = "osx" ]; then brew update; fi
  - if [ $TRAVIS_OS_NAME = "osx" ]; then brew install trash; fi