version: 2
jobs:
  build_trash_cli:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/Bios-Marcel/wastebasket
    steps:
      - checkout

      - run: sudo apt-get update
      - run: sudo apt-get -y install trash-cli
      
      - run: go get -v -t -d ./...
      - run: go test -v ./...

  build_gvfs:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/Bios-Marcel/wastebasket
    steps:
      - checkout

      - run: sudo apt-get update
      - run: sudo apt-get -y install gvfs gvfs-common gvfs-bin
      
      - run: go get -v -t -d ./...
      - run: go test -v ./...

  build_gio:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/Bios-Marcel/wastebasket
    steps:
      - checkout
      
      - run: sudo apt-get update
      - run: sudo apt-get -y install libglib2.0
      
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      
workflows:
  version: 2
  build:
    jobs:
      - build_gvfs
      - build_trash_cli
      - build_gio