name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest]
        go: ['1.23.x']

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Run tests
        shell: bash
        run: |
          go test -race -v -covermode=atomic ./...
