name: Build

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        include:
          - platform: windows-latest
            binary_name: wastebasket-x64.exe
          - platform: ubuntu-latest
            binary_name: wastebasket-linux-x64
          - platform: macos-latest
            binary_name: wastebasket-macos-x64

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Run tests
        shell: bash
        run: |
          go test -race -v -covermode=atomic ./...

      - name: Build artifact
        shell: bash
        run: |
          go build -trimpath -ldflags "-w -s" -o ${{ matrix.binary_name }} ./cmd/wastebasket

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.binary_name }}
          path: ./${{ matrix.binary_name }}
